services:
  nodejs:
    build: .
    image: nodejs # nome personalizado para a imagem
    volumes:
      - ".:/var/www/app" # os dois pontos servem para monitorar os arquivos na pasta
    ports:
      - "8070:8070"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - "${POSTGRES_PORT}:5432" 