services:
  nodejs:
    build: .
    volumes:
      - ".:/var/www/app"
    ports:
      - "8070:8070"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${EXAMPLE_DB} 
    ports:
      - "${POSTGRES_PORT}:5432" 